// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuPkGLWLwG1kGjGOLw-SNO3WkIXsKzXwY',
    appId: '1:27772756950:web:9f9cb624a1cde625d33a77',
    messagingSenderId: '27772756950',
    projectId: 'toba-bersih',
    authDomain: 'toba-bersih.firebaseapp.com',
    storageBucket: 'toba-bersih.firebasestorage.app',
    measurementId: 'G-273LN5J3TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDK2ixuqri5IBVEMJXfM9SUfyPVg6b3yk',
    appId: '1:27772756950:android:d6a11460afa95773d33a77',
    messagingSenderId: '27772756950',
    projectId: 'toba-bersih',
    storageBucket: 'toba-bersih.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkeCd85y-5-6EUlBnbu1FXt4jraEcq5po',
    appId: '1:27772756950:ios:51eb6e98bae98090d33a77',
    messagingSenderId: '27772756950',
    projectId: 'toba-bersih',
    storageBucket: 'toba-bersih.firebasestorage.app',
    iosBundleId: 'com.example.tobaBersih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkeCd85y-5-6EUlBnbu1FXt4jraEcq5po',
    appId: '1:27772756950:ios:51eb6e98bae98090d33a77',
    messagingSenderId: '27772756950',
    projectId: 'toba-bersih',
    storageBucket: 'toba-bersih.firebasestorage.app',
    iosBundleId: 'com.example.tobaBersih',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuPkGLWLwG1kGjGOLw-SNO3WkIXsKzXwY',
    appId: '1:27772756950:web:97e5d8a7d860a713d33a77',
    messagingSenderId: '27772756950',
    projectId: 'toba-bersih',
    authDomain: 'toba-bersih.firebaseapp.com',
    storageBucket: 'toba-bersih.firebasestorage.app',
    measurementId: 'G-LHYGN97Z1T',
  );
}
